security.user:
  name: foo
  password: bar

management.info.git.mode: full

spring.application.name: sigla-print

scheduler.print: 10000

spring.jpa:
  hibernate.ddl-auto: none # update per generazione schema
  properties.hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
#  database-platform: org.hibernate.dialect.Oracle10gDialect

spring.datasource:
  url: jdbc:oracle:thin:@dbtest.cedrc.cnr.it:1521:SIGLAF
  username: PCIR009
  password: dbform
  driverClassName: oracle.jdbc.OracleDriver