spring.jpa:
  hibernate.ddl-auto: none # update per generazione schema
  properties:
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate.connection.autocommit: false
#  database-platform: org.hibernate.dialect.Oracle10gDialect

spring.datasource:
  url: jdbc:oracle:thin:@dbtest.cedrc.cnr.it:1521:SIGLAF
  username: PCIR009
  password: dbform
  driverClassName: oracle.jdbc.OracleDriver