security.user:
  name: foo
  password: bar

management.info.git.mode: full

spring.application.name: sigla-print

scheduler.print: 60000

queue.sigla.priorita: 1,2,3,9

cnr.gitlab:
  url: http://git.si.cnr.it/dev/sigla-common/raw/master/SIGLAReports/reports
  token: TyB9NvodV1sDyroHF4zQ

logging.level.it.cnr: DEBUG
logging.level.org.springframework.cache: TRACE
logging.pattern.console: "%date |%-5level| [%thread] [%file:%line] - %msg%n%ex{full}"
