security.basic.enabled: false

management.info.git.mode: full

spring.application.name: sigla-print-multi-impegni
spring.mail.host: smtp.amministrazione.cnr.it
spring.mail.username: amministrazione_sigla
spring.mail.***REMOVED***
spring.mail.from: sigla@cnr.it

print:
  output.dir: ${user.home}/print
  server.url: http://localhost:8080
  scheduler: 5000
  deletecron: 0 0 2 1/1 * ?
  queue.priorita: 1,2,3
  max.page.size: 1000

cnr:
  gitlab:
    url: http://git.si.cnr.it/dev/sigla-reports/raw/multi-impegni
    token: TyB9NvodV1sDyroHF4zQ
  ajp:
    port: 8009
    timeout: 120000
  cache.hazelcast.packages: it.cnr

logging.config: classpath:logback-local.xml

spring.jpa:
  hibernate.ddl-auto: none # update per generazione schema
  properties:
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate.connection.autocommit: false
#  database-platform: org.hibernate.dialect.Oracle10gDialect

spring.datasource:
  url: jdbc:oracle:thin:@dbtest.cedrc.cnr.it:1521:SIGLAT
  username: PCIR009
  password: dbtest
  driverClassName: oracle.jdbc.OracleDriver

dir.image: /img/
