spring:
  application:
    name: sigla-print
  mail:
    host: smtp.amministrazione.cnr.it
    username:
    password:
    from: sigla@cnr.it
    smtp:
      auth: false
  jpa:
    hibernate.ddl-auto: none # update per generazione schema
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
      hibernate.connection.autocommit: false
  #  database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:oracle:thin:@dbtest.cedrc.cnr.it:1521:SIGLAF
    username: PCIR009
    password: dbform
    driverClassName: oracle.jdbc.OracleDriver

print:
  output.dir: ${user.home}/print
  server.url: http://localhost:8080
  scheduler: 5000
  deletecron: 0 0 2 1/1 * ?
  queue.priorita: 1,2,3,4,5
  max.page.size: 1000
  virtualizer.enable: true

cnr:
  ajp:
    port: 8009
    timeout: 120000
  cache:
    hazelcast:
      packages: it.cnr

logging.config: classpath:logback-local.xml

dir.image: /img/

management:
  endpoints:
    web:
      base-path: /